apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rest-api-go.fullname" . }}
  labels:
    app: {{ include "rest-api-go.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "rest-api-go.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "rest-api-go.name" . }}
    spec:
      containers:
      - name: {{ include "rest-api-go.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: DB_HOST
          value: "{{ .Values.database.host }}"
        - name: DB_PORT
          value: "{{ .Values.database.port }}"
        envFrom:
        - secretRef:
            name: {{ .Values.database.secretName }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}