{{- if .Values.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "rest-api-go.fullname" . }}-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "rest-api-go.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode }}
{{- end }}
