# values.yaml
replicaCount: 2

image:
  repository: ciulik/rest-api-go-mgr
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60

vpa:
  enabled: true
  updateMode: "Auto"

postgres:
  image: postgres:latest
  replicaCount: 1
  db: mydb
  host: postgres
  servicePort: 5432
  secretName: db-secret